[package]
name = "jasmine_core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[features]
uniffi-cli = ["uniffi/cli"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"
required-features = ["uniffi-cli"]

[dependencies]
uniffi = "0.32.0"

[build-dependencies]
uniffi = { version = "0.32.0", features = ["build"] }
